### ISSUE TITLE
Property ChamberTemperatures not found

### ISSUE THREAD

**Issue by DerGolo** [Schnittcher/OctoPrint#1]
Although I disabled the chamber temperatures in the OctoTemperatures instance, the error ist raised every second.

<img width="1040" alt="2021-07-17_15-59-52 (1)" src="https://user-images.githubusercontent.com/35155617/126039597-b348bee5-d9cd-41a9-986f-91559a289800.png">

**Comment by Schnittcher** [comment]
Ist in der aktuellen Version gefixt.

**Comment by DerGolo** [comment]
Das sieht gut aus :-) Es scheint noch ein Debug aktiv zu sein, der Sekündlich logged:

![image](https://user-images.githubusercontent.com/35155617/126888823-a2ed6b09-24b1-427b-91f4-6bdeef10e180.png)
